/*
 ============================================================================
 Name        : hev-main-rust.h
 Auto-generated by cbindgen from hs5t-core (feature = "c-api")
 ============================================================================
 */

#ifndef __HEV_MAIN_RUST_H__
#define __HEV_MAIN_RUST_H__

/* This file is auto-generated by cbindgen. DO NOT EDIT. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/*
 Start the tunnel using a configuration file.  Blocks until quit or error.

 Returns 0 on success, -1 on error.

 # Safety

 `config_path` must be a valid, null-terminated C string.
 */
int hev_socks5_tunnel_main_from_file(const char *config_path, int tun_fd);

/*
 Legacy alias for `hev_socks5_tunnel_main_from_file`.

 # Safety

 Same as `hev_socks5_tunnel_main_from_file`.
 */
int hev_socks5_tunnel_main(const char *config_path, int tun_fd);

/*
 Start the tunnel using an in-memory YAML config string.  Blocks until quit or error.

 Returns 0 on success, -1 on error.

 # Safety

 `config_str` must point to `config_len` valid, UTF-8 bytes.
 */
int hev_socks5_tunnel_main_from_str(const uint8_t *config_str, unsigned int config_len, int tun_fd);

/*
 Cancel the running tunnel.  Safe to call from any thread.
 */
void hev_socks5_tunnel_quit(void);

/*
 Write traffic statistics to the provided out-parameters.

 # Safety

 All four pointer arguments must be valid, non-null, writable `size_t`
 locations.  The function writes atomically-snapshotted counters.
 */
void hev_socks5_tunnel_stats(size_t *tx_packets,
                             size_t *tx_bytes,
                             size_t *rx_packets,
                             size_t *rx_bytes);

#endif  /* __HEV_MAIN_RUST_H__ */
